# Generated by Django 5.0 on 2024-01-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonorApp', '0002_donorinfo_bloodtype_donorinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorinfo',
            name='city',
            field=models.CharField(default='london', max_length=100),
        ),
        migrations.AddField(
            model_name='donorinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donor_images'),
        ),
    ]
